### ISSUE TITLE
[request] Submenus

### ISSUE THREAD

**Issue by azev** [pawelt/stacky#10]
Hi, is it possible to put items in subfolders in submenus?
For example:
c:\mymenu\app1.lnk
c:\mymenu\app2.lnk
c:\mymenu\group1\app3.lnk
c:\mymenu\group1\app4.lnk
c:\mymenu\group2\app5.lnk
c:\mymenu\group2\app6.lnk

![Untitled](https://user-images.githubusercontent.com/6639188/124962659-4571ce80-dff5-11eb-8022-3669b24b2745.png)

**Comment by pawelt** [comment]
I don't think it was possible, no.

Sorry for a rather later response. I am not maintaining the project anymore. Please feel free to fork it and change it in any way you want. Good luck! :)

**Comment by clau-bucur** [comment]
You can check out [my fork](https://github.com/clau-bucur/stacky/) for a fix.
