### ISSUE TITLE
How about multiple monitors setup support?

### ISSUE THREAD

**Issue by egigoka** [pawelt/stacky#3]
Opening stacky from non-main screen still open it on main screen.
![image](https://user-images.githubusercontent.com/23525323/59926649-6df4f300-9443-11e9-8f31-83d7be2decae.png)
![image](https://user-images.githubusercontent.com/23525323/59926659-73ead400-9443-11e9-878c-9036629d7d41.png)

**Comment by egigoka** [comment]
Fixed :3 
#4

**Comment by pawelt** [comment]
Sorry for a rather later response. I am not maintaining the project anymore. Please feel free to fork it and change it in any way you want. Good luck! :)
