### ISSUE TITLE
Please add darkmode support

### ISSUE THREAD

**Issue by midgreezy** [pawelt/stacky#6]
Hopefully a small request.

Love your work. Thanks.

**Comment by AnnanFay** [comment]
I briefly looked into this, in case it was something really simple. From what I can tell it'll take more than a few lines of code.

If someone gets round to it https://github.com/ysc3839/win32-darkmode looks like a promising starting place.

And [this related stackoverflow thread](https://stackoverflow.com/questions/53501268/win10-dark-theme-how-to-use-in-winapi).

**Comment by dvoijen** [comment]
Would like to see that too, i use this now in Windows 11 and i must say it is an outcome :D

**Comment by pawelt** [comment]
Sorry for a rather later response. I am not maintaining the project anymore. Please feel free to fork it and change it in any way you want. Good luck! :)

**Comment by clau-bucur** [comment]
You can check out [my fork](https://github.com/clau-bucur/stacky/) for a fix.
It's a partial fix unfortunatelly, I was unable to completely darken it, the shadow still remains light...
