### ISSUE TITLE
[request] Remove 1st entry ("Open [folder]")

### ISSUE THREAD

**Issue by azev** [pawelt/stacky#9]
Is it possible to not display the 1st menu entry "Open [folder]"?

Amazing program! ++

**Comment by jdrox** [comment]
I would love to have the top menu entry removed as well.  thank you!

**Comment by pawelt** [comment]
Thank you :)

Sorry for a rather later response. I am not maintaining the project anymore. Please feel free to fork it and change it in any way you want. Good luck! :)

**Comment by clau-bucur** [comment]
You can check out [my fork](https://github.com/clau-bucur/stacky/) for a fix.
